import type { ComplianceRule } from '../types/compliance.js';

/**
 * Default compliance audit rules
 */
export const DEFAULT_AUDIT_RULES: ComplianceRule[] = [
  {
    id: 'AC-001',
    name: 'Inactive Members',
    description: 'Detect organization members who have not been active for over 90 days',
    category: 'access-control',
    severity: 'medium',
    enabled: true,
    checker: 'checkInactiveMembers',
    params: { inactiveDays: 90 },
  },
  {
    id: 'AC-002',
    name: 'Excessive Admin Roles',
    description: 'Warn when more than 20% of members have owner or admin roles',
    category: 'access-control',
    severity: 'high',
    enabled: true,
    checker: 'checkExcessiveAdmins',
    params: { maxAdminPercentage: 20 },
  },
  {
    id: 'AC-003',
    name: 'Single Primary Owner',
    description: 'Verify there is exactly one primary owner (no orphaned or duplicate)',
    category: 'access-control',
    severity: 'critical',
    enabled: true,
    checker: 'checkPrimaryOwner',
    params: {},
  },
  {
    id: 'AK-001',
    name: 'Unused API Keys',
    description: 'Detect API keys that have not been used in the last 30 days',
    category: 'api-key-management',
    severity: 'medium',
    enabled: true,
    checker: 'checkUnusedApiKeys',
    params: { unusedDays: 30 },
  },
  {
    id: 'AK-002',
    name: 'Unscoped API Keys',
    description: 'Detect API keys that are not scoped to specific workspaces',
    category: 'api-key-management',
    severity: 'high',
    enabled: true,
    checker: 'checkUnscopedApiKeys',
    params: {},
  },
  {
    id: 'AK-003',
    name: 'API Key Age',
    description: 'Warn about API keys older than 180 days that should be rotated',
    category: 'api-key-management',
    severity: 'medium',
    enabled: true,
    checker: 'checkApiKeyAge',
    params: { maxAgeDays: 180 },
  },
  {
    id: 'UA-001',
    name: 'Usage Spike Detection',
    description: 'Detect unusual spikes in token usage compared to the 7-day average',
    category: 'usage-anomaly',
    severity: 'high',
    enabled: true,
    checker: 'checkUsageSpike',
    params: { spikeMultiplier: 3.0 },
  },
  {
    id: 'UA-002',
    name: 'Cost Budget Threshold',
    description: 'Alert when monthly cost exceeds the configured budget threshold',
    category: 'usage-anomaly',
    severity: 'critical',
    enabled: true,
    checker: 'checkCostBudget',
    params: { monthlyBudgetUsd: 10000 },
  },
  {
    id: 'DG-001',
    name: 'Empty Workspaces',
    description: 'Detect workspaces with no members that may need cleanup',
    category: 'data-governance',
    severity: 'low',
    enabled: true,
    checker: 'checkEmptyWorkspaces',
    params: {},
  },
  {
    id: 'OP-001',
    name: 'Collection Freshness',
    description: 'Warn if audit data has not been collected in the last 24 hours',
    category: 'operational',
    severity: 'high',
    enabled: true,
    checker: 'checkCollectionFreshness',
    params: { maxStaleHours: 24 },
  },
];
